name: Unsplash
options:
  xcodeVersion: 13.0
configs:
  Production: release
  Develop: debug
options:
  deploymentTarget:
    iOS: '14.0'
  defaultConfig: Develop
  bundleIdPrefix: ru
  groupSortPosition: top
  developmentLanguage: "ru"
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  groupOrdering:
    - order: [Sources, Supporting Files]
    - pattern: 'Unsplash'
      order: [Application, Common, Protocols, Extensions, Modules, Views, Services, Utils]
settings:
  base:
    SWIFT_VERSION: 5.7
    TARGETED_DEVICE_FAMILY: 1
  configs:
    Production:
      SWIFT_COMPILATION_MODE: "wholemodule"
    Develop:
      SWIFT_COMPILATION_MODE: "incremental"
targets:
  Unsplash:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - Unsplash
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: Supporting Files/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ru.unsplash
    postBuildScripts:
    - script: |
        export PATH="$PATH:/opt/homebrew/bin"
        if which swiftlint > /dev/null; then
          swiftlint
        else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
        fi
      name: Run SwiftLint
    - script: |
